### ISSUE TITLE
npm-release is failing due to assertion error that should not be occurring

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE.Shared#405]
```
> @halospv3/hce.shared-config@2.3.1 test
> node --test --import tsx ./tests/**/*.test.ts

TAP version 13
# Subtest: MSBuildProject
ok 1 - MSBuildProject # TODO custom properties?
  ---
  duration_ms: 1.300451
  ...
# Subtest: MSBuildProjectProperties
ok 2 - MSBuildProjectProperties # TODO
  ---
  duration_ms: 1.114886
  ...
# Subtest: dotnetGHPR
    # Subtest: getNugetGitHubUrl
        # Subtest: returns string when GITHUB_REPOSITORY_OWNER is defined
        ok 1 - returns string when GITHUB_REPOSITORY_OWNER is defined
          ---
          duration_ms: 1.554373
          ...
        # Subtest: returns undefined when GITHUB_REPOSITORY_OWNER is undefined
        ok 2 - returns undefined when GITHUB_REPOSITORY_OWNER is undefined
          ---
          duration_ms: 0.190806
          ...
        1..2
    ok 1 - getNugetGitHubUrl
      ---
      duration_ms: 2.668918
      type: 'suite'
      ...
    # Subtest: isTokenDefined
        # Subtest: is a function
        ok 1 - is a function
          ---
          duration_ms: 0.453284
          ...
        # Subtest: returns true when custom token is defined
        ok 2 - returns true when custom token is defined
          ---
          duration_ms: 0.504699
          ...
        # Subtest: returns false when custom token is undefined
        ok 3 - returns false when custom token is undefined
          ---
          duration_ms: 0.166349
          ...
        # Subtest: returns true when GITHUB_TOKEN is defined
        ok 4 - returns true when GITHUB_TOKEN is defined
          ---
          duration_ms: 0.290882
          ...
        # Subtest: returns true and fallback:"GH_TOKEN" when GITHUB_TOKEN is undefined, but fallback GH_TOKEN is defined
        ok 5 - returns true and fallback:"GH_TOKEN" when GITHUB_TOKEN is undefined, but fallback GH_TOKEN is defined
          ---
          duration_ms: 0.202998
          ...
        # Subtest: returns false and fallback:"GH_TOKEN" when GITHUB_TOKEN and GH_TOKEN are undefined
        ok 6 - returns false and fallback:"GH_TOKEN" when GITHUB_TOKEN and GH_TOKEN are undefined
          ---
          duration_ms: 0.911116
          ...
        1..6
    ok 2 - isTokenDefined
      ---
      duration_ms: 3.058494
      type: 'suite'
      ...
    # Subtest: getGithubNugetRegistryPair
        # Subtest: getGitHubNugetRegistryPair is function
        ok 1 - getGitHubNugetRegistryPair is function
          ---
          duration_ms: 0.339873
          ...
        # Subtest: can return when classic or workflow GITHUB_TOKEN or GH_TOKEN is defined with write:packages.
        not ok 2 - can return when classic or workflow GITHUB_TOKEN or GH_TOKEN is defined with write:packages.
          ---
          duration_ms: 9.739429
          location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:3360'
          failureType: 'testCodeFailure'
          error: |-
            Expected values to be strictly equal:
            + actual - expected
            
            + TypeError: The environment variable GITHUB_TOKEN is undefined!
            +     at tokenCanWritePackages (/home/runner/work/HCE.Shared/HCE.Shared/cjs/dotnet/dotnetGHPR.cjs:17:39)
            +     at TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:154:31)
            +     at Test.runInAsyncScope (node:async_hooks:206:9)
            +     at Test.run (node:internal/test_runner/test:824:25)
            +     at Suite.processPendingSubtests (node:internal/test_runner/test:533:18)
            +     at Test.postRun (node:internal/test_runner/test:923:19)
            +     at Test.run (node:internal/test_runner/test:866:12)
            +     at async Promise.all (index 0)
            +     at async Suite.run (node:internal/test_runner/test:1183:7)
            +     at async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)
            - true
          code: 'ERR_ASSERTION'
          name: 'AssertionError'
          expected: true
          actual:
          error: 'The environment variable GITHUB_TOKEN is undefined!'
          name: 'TypeError'
          stack: |-
            tokenCanWritePackages (/home/runner/work/HCE.Shared/HCE.Shared/cjs/dotnet/dotnetGHPR.cjs:17:39)
            TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:154:31)
            Test.runInAsyncScope (node:async_hooks:206:9)
            Test.run (node:internal/test_runner/test:824:25)
            Suite.processPendingSubtests (node:internal/test_runner/test:533:18)
            Test.postRun (node:internal/test_runner/test:923:19)
            Test.run (node:internal/test_runner/test:866:12)
            async Promise.all (index 0)
            async Suite.run (node:internal/test_runner/test:1183:7)
            async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)
          operator: 'strictEqual'
          stack: |-
            TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:161:5)
            async Test.run (node:internal/test_runner/test:825:9)
            async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)
          ...
        # Subtest: mock insufficient token
        ok 3 - mock insufficient token # TODO
          ---
          duration_ms: 0.143618
          ...
        # Subtest: mock sufficient token
        ok 4 - mock sufficient token # TODO
          ---
          duration_ms: 0.141574
          ...
        # Subtest: mock custom url
        ok 5 - mock custom url # TODO
          ---
          duration_ms: 0.117739
          ...
        1..5
    not ok 3 - getGithubNugetRegistryPair
      ---
      duration_ms: 10.990448
      type: 'suite'
      location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:2842'
      failureType: 'subtestsFailed'
      error: '1 subtest failed'
      code: 'ERR_TEST_FAILURE'
      ...
    1..3
not ok 3 - dotnetGHPR
  ---
  duration_ms: 17.527646
  type: 'suite'
  location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:708'
  failureType: 'subtestsFailed'
  error: '1 subtest failed'
  code: 'ERR_TEST_FAILURE'
  ...
# Subtest: dotnetGLPR
    # Subtest: GitLabTokenEnvVar
    ok 1 - GitLabTokenEnvVar
      ---
      duration_ms: 0.423308
      type: 'suite'
      ...
    # Subtest: nugetGitLabUrlBase
    ok 2 - nugetGitLabUrlBase
      ---
      duration_ms: 0.209459
      type: 'suite'
      ...
    # Subtest: nugetGitLabUrl
    ok 3 - nugetGitLabUrl
      ---
      duration_ms: 0.120995
      type: 'suite'
      ...
    # Subtest: getGitlabNugetRegistryPair
        # Subtest: is a function
        ok 1 - is a function
          ---
          duration_ms: 0.713669
          ...
        # Subtest: sufficient token permissions
        ok 2 - sufficient token permissions # TODO
          ---
          duration_ms: 0.132396
          ...
        # Subtest: insufficient token permissions
        ok 3 - insufficient token permissions # TODO
          ---
          duration_ms: 0.180176
          ...
        # Subtest: custom url
        ok 4 - custom url # TODO
          ---
          duration_ms: 0.206825
          ...
        # Subtest: custom token
        ok 5 - custom token # TODO
          ---
          duration_ms: 0.141243
          ...
        1..5
    ok 4 - getGitlabNugetRegistryPair
      ---
      duration_ms: 2.31521
      type: 'suite'
      ...
    1..4
ok 4 - dotnetGLPR
  ---
  duration_ms: 4.671677
  type: 'suite'
  ...
# Subtest: dotnetHelpers
    # Subtest: configurePrepareCmd
    ok 1 - configurePrepareCmd # TODO
      ---
      duration_ms: 1.216906
      ...
    # Subtest: nugetDefault is as expected
    ok 2 - nugetDefault is as expected
      ---
      duration_ms: 0.707157
      ...
    # Subtest: configureDotnetNugetPush works
    ok 3 - configureDotnetNugetPush works # TODO pushToGitHub adds github defaults
      ---
      duration_ms: 0.152414
      ...
    1..3
ok 5 - dotnetHelpers
  ---
  duration_ms: 3.718673
  type: 'suite'
  ...
1..5
# tests 23
# suites 10
# pass 11
# fail 1
# cancelled 0
# skipped 0
# todo 11
# duration_ms 468.588179
husky - pre-commit script failed (code 1)
    at makeError (/home/runner/work/HCE.Shared/HCE.Shared/node_modules/@semantic-release/git/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/HCE.Shared/HCE.Shared/node_modules/@semantic-release/git/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async commit (/home/runner/work/HCE.Shared/HCE.Shared/node_modules/@semantic-release/git/lib/git.js:38:3)
    at async module.exports (/home/runner/work/HCE.Shared/HCE.Shared/node_modules/@semantic-release/git/lib/prepare.js:63:5)
    at async prepare (/home/runner/work/HCE.Shared/HCE.Shared/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (file:///home/runner/work/HCE.Shared/HCE.Shared/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///home/runner/work/HCE.Shared/HCE.Shared/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///home/runner/work/HCE.Shared/HCE.Shared/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
  shortMessage: 'Command failed with exit code 1: git commit -m chore(release): 2.5.0 [skip ci]\n' +
    '\n' +
    '## [2.5.0](https://github.com/halospv3/hce.shared/compare/v2.4.3...v2.5.0) (2024-06-04)\n' +
    '\n' +
    '### Features\n' +
    '\n' +
    '* overhaul dotnetGHPR; misc refactors ([8d0a1d6](https://github.com/halospv3/hce.shared/commit/8d0a1d657e7f4754881c9a130fd4aa8191fb3e81))\n' +
    '\n' +
    '### Bug Fixes\n' +
    '\n' +
    '* **deps:** update dependency conventional-changelog-conventionalcommits to v8 ([e1defcd](https://github.com/halospv3/hce.shared/commit/e1defcd94ba51eda7384c1ca87f33c9928610e20))\n' +
    '* **deps:** update semantic-release monorepo ([39fcf98](https://github.com/halospv3/hce.shared/commit/39fcf988fe55b894e269d64de1b48c7f8dfb950c))\n',
  command: 'git commit -m chore(release): 2.5.0 [skip ci]\n' +
    '\n' +
    '## [2.5.0](https://github.com/halospv3/hce.shared/compare/v2.4.3...v2.5.0) (2024-06-04)\n' +
    '\n' +
    '### Features\n' +
    '\n' +
    '* overhaul dotnetGHPR; misc refactors ([8d0a1d6](https://github.com/halospv3/hce.shared/commit/8d0a1d657e7f4754881c9a130fd4aa8191fb3e81))\n' +
    '\n' +
    '### Bug Fixes\n' +
    '\n' +
    '* **deps:** update dependency conventional-changelog-conventionalcommits to v8 ([e1defcd](https://github.com/halospv3/hce.shared/commit/e1defcd94ba51eda7384c1ca87f33c9928610e20))\n' +
    '* **deps:** update semantic-release monorepo ([39fcf98](https://github.com/halospv3/hce.shared/commit/39fcf988fe55b894e269d64de1b48c7f8dfb950c))\n',
  escapedCommand: 'git commit -m "chore(release): 2.5.0 [skip ci]\n' +
    '\n' +
    '## [2.5.0](https://github.com/halospv3/hce.shared/compare/v2.4.3...v2.5.0) (2024-06-04)\n' +
    '\n' +
    '### Features\n' +
    '\n' +
    '* overhaul dotnetGHPR; misc refactors ([8d0a1d6](https://github.com/halospv3/hce.shared/commit/8d0a1d657e7f4754881c9a130fd4aa8191fb3e81))\n' +
    '\n' +
    '### Bug Fixes\n' +
    '\n' +
    '* **deps:** update dependency conventional-changelog-conventionalcommits to v8 ([e1defcd](https://github.com/halospv3/hce.shared/commit/e1defcd94ba51eda7384c1ca87f33c9928610e20))\n' +
    '* **deps:** update semantic-release monorepo ([39fcf98](https://github.com/halospv3/hce.shared/commit/39fcf988fe55b894e269d64de1b48c7f8dfb950c))\n' +
    '"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '\n' +
    '> @halospv3/hce.shared-config@2.3.1 check\n' +
    '> npm run type && npm run test && npm run lint\n' +
    '\n' +
    '\n' +
    '> @halospv3/hce.shared-config@2.3.1 type\n' +
    '> tsc --build\n' +
    '\n' +
    '\n' +
    '> @halospv3/hce.shared-config@2.3.1 pretest\n' +
    '> npm run build\n' +
    '\n' +
    '\n' +
    '> @halospv3/hce.shared-config@2.3.1 build\n' +
    '> packemon build --addExports --addFiles --declaration --loadConfigs\n' +
    '\n' +
    '[@halospv3/hce.shared-config:HCE] Entry module "src/semanticReleaseConfigDotnet.ts" is using named and default exports together. Consumers of your bundle will have to use `chunk.default` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning. (id=/home/runner/work/HCE.Shared/HCE.Shared/src/semanticReleaseConfigDotnet.ts)\n' +
    '@halospv3/hce.shared-config\n' +
    '  ◼ cjs (38.87 kB) ◼ dts 2.2s\n' +
    '\n' +
    '> @halospv3/hce.shared-config@2.3.1 test\n' +
    '> node --test --import tsx ./tests/**/*.test.ts\n' +
    '\n' +
    'TAP version 13\n' +
    '# Subtest: MSBuildProject\n' +
    'ok 1 - MSBuildProject # TODO custom properties?\n' +
    '  ---\n' +
    '  duration_ms: 1.300451\n' +
    '  ...\n' +
    '# Subtest: MSBuildProjectProperties\n' +
    'ok 2 - MSBuildProjectProperties # TODO\n' +
    '  ---\n' +
    '  duration_ms: 1.114886\n' +
    '  ...\n' +
    '# Subtest: dotnetGHPR\n' +
    '    # Subtest: getNugetGitHubUrl\n' +
    '        # Subtest: returns string when GITHUB_REPOSITORY_OWNER is defined\n' +
    '        ok 1 - returns string when GITHUB_REPOSITORY_OWNER is defined\n' +
    '          ---\n' +
    '          duration_ms: 1.554373\n' +
    '          ...\n' +
    '        # Subtest: returns undefined when GITHUB_REPOSITORY_OWNER is undefined\n' +
    '        ok 2 - returns undefined when GITHUB_REPOSITORY_OWNER is undefined\n' +
    '          ---\n' +
    '          duration_ms: 0.190806\n' +
    '          ...\n' +
    '        1..2\n' +
    '    ok 1 - getNugetGitHubUrl\n' +
    '      ---\n' +
    '      duration_ms: 2.668918\n' +
    "      type: 'suite'\n" +
    '      ...\n' +
    '    # Subtest: isTokenDefined\n' +
    '        # Subtest: is a function\n' +
    '        ok 1 - is a function\n' +
    '          ---\n' +
    '          duration_ms: 0.453284\n' +
    '          ...\n' +
    '        # Subtest: returns true when custom token is defined\n' +
    '        ok 2 - returns true when custom token is defined\n' +
    '          ---\n' +
    '          duration_ms: 0.504699\n' +
    '          ...\n' +
    '        # Subtest: returns false when custom token is undefined\n' +
    '        ok 3 - returns false when custom token is undefined\n' +
    '          ---\n' +
    '          duration_ms: 0.166349\n' +
    '          ...\n' +
    '        # Subtest: returns true when GITHUB_TOKEN is defined\n' +
    '        ok 4 - returns true when GITHUB_TOKEN is defined\n' +
    '          ---\n' +
    '          duration_ms: 0.290882\n' +
    '          ...\n' +
    '        # Subtest: returns true and fallback:"GH_TOKEN" when GITHUB_TOKEN is undefined, but fallback GH_TOKEN is defined\n' +
    '        ok 5 - returns true and fallback:"GH_TOKEN" when GITHUB_TOKEN is undefined, but fallback GH_TOKEN is defined\n' +
    '          ---\n' +
    '          duration_ms: 0.202998\n' +
    '          ...\n' +
    '        # Subtest: returns false and fallback:"GH_TOKEN" when GITHUB_TOKEN and GH_TOKEN are undefined\n' +
    '        ok 6 - returns false and fallback:"GH_TOKEN" when GITHUB_TOKEN and GH_TOKEN are undefined\n' +
    '          ---\n' +
    '          duration_ms: 0.911116\n' +
    '          ...\n' +
    '        1..6\n' +
    '    ok 2 - isTokenDefined\n' +
    '      ---\n' +
    '      duration_ms: 3.058494\n' +
    "      type: 'suite'\n" +
    '      ...\n' +
    '    # Subtest: getGithubNugetRegistryPair\n' +
    '        # Subtest: getGitHubNugetRegistryPair is function\n' +
    '        ok 1 - getGitHubNugetRegistryPair is function\n' +
    '          ---\n' +
    '          duration_ms: 0.339873\n' +
    '          ...\n' +
    '        # Subtest: can return when classic or workflow GITHUB_TOKEN or GH_TOKEN is defined with write:packages.\n' +
    '        not ok 2 - can return when classic or workflow GITHUB_TOKEN or GH_TOKEN is defined with write:packages.\n' +
    '          ---\n' +
    '          duration_ms: 9.739429\n' +
    "          location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:3360'\n" +
    "          failureType: 'testCodeFailure'\n" +
    '          error: |-\n' +
    '            Expected values to be strictly equal:\n' +
    '            + actual - expected\n' +
    '            \n' +
    '            + TypeError: The environment variable GITHUB_TOKEN is undefined!\n' +
    '            +     at tokenCanWritePackages (/home/runner/work/HCE.Shared/HCE.Shared/cjs/dotnet/dotnetGHPR.cjs:17:39)\n' +
    '            +     at TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:154:31)\n' +
    '            +     at Test.runInAsyncScope (node:async_hooks:206:9)\n' +
    '            +     at Test.run (node:internal/test_runner/test:824:25)\n' +
    '            +     at Suite.processPendingSubtests (node:internal/test_runner/test:533:18)\n' +
    '            +     at Test.postRun (node:internal/test_runner/test:923:19)\n' +
    '            +     at Test.run (node:internal/test_runner/test:866:12)\n' +
    '            +     at async Promise.all (index 0)\n' +
    '            +     at async Suite.run (node:internal/test_runner/test:1183:7)\n' +
    '            +     at async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n' +
    '            - true\n' +
    "          code: 'ERR_ASSERTION'\n" +
    "          name: 'AssertionError'\n" +
    '          expected: true\n' +
    '          actual:\n' +
    "          error: 'The environment variable GITHUB_TOKEN is undefined!'\n" +
    "          name: 'TypeError'\n" +
    '          stack: |-\n' +
    '            tokenCanWritePackages (/home/runner/work/HCE.Shared/HCE.Shared/cjs/dotnet/dotnetGHPR.cjs:17:39)\n' +
    '            TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:154:31)\n' +
    '            Test.runInAsyncScope (node:async_hooks:206:9)\n' +
    '            Test.run (node:internal/test_runner/test:824:25)\n' +
    '            Suite.processPendingSubtests (node:internal/test_runner/test:533:18)\n' +
    '            Test.postRun (node:internal/test_runner/test:923:19)\n' +
    '            Test.run (node:internal/test_runner/test:866:12)\n' +
    '            async Promise.all (index 0)\n' +
    '            async Suite.run (node:internal/test_runner/test:1183:7)\n' +
    '            async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n' +
    "          operator: 'strictEqual'\n" +
    '          stack: |-\n' +
    '            TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:161:5)\n' +
    '            async Test.run (node:internal/test_runner/test:825:9)\n' +
    '            async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n' +
    '          ...\n' +
    '        # Subtest: mock insufficient token\n' +
    '        ok 3 - mock insufficient token # TODO\n' +
    '          ---\n' +
    '          duration_ms: 0.143618\n' +
    '          ...\n' +
    '        # Subtest: mock sufficient token\n' +
    '        ok 4 - mock sufficient token # TODO\n' +
    '          ---\n' +
    '          duration_ms: 0.141574\n' +
    '          ...\n' +
    '        # Subtest: mock custom url\n' +
    '        ok 5 - mock custom url # TODO\n' +
    '          ---\n' +
    '          duration_ms: 0.117739\n' +
    '          ...\n' +
    '        1..5\n' +
    '    not ok 3 - getGithubNugetRegistryPair\n' +
    '      ---\n' +
    '      duration_ms: 10.990448\n' +
    "      type: 'suite'\n" +
    "      location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:2842'\n" +
    "      failureType: 'subtestsFailed'\n" +
    "      error: '1 subtest failed'\n" +
    "      code: 'ERR_TEST_FAILURE'\n" +
    '      ...\n' +
    '    1..3\n' +
    'not ok 3 - dotnetGHPR\n' +
    '  ---\n' +
    '  duration_ms: 17.527646\n' +
    "  type: 'suite'\n" +
    "  location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:708'\n" +
    "  failureType: 'subtestsFailed'\n" +
    "  error: '1 subtest failed'\n" +
    "  code: 'ERR_TEST_FAILURE'\n" +
    '  ...\n' +
    '# Subtest: dotnetGLPR\n' +
    '    # Subtest: GitLabTokenEnvVar\n' +
    '    ok 1 - GitLabTokenEnvVar\n' +
    '      ---\n' +
    '      duration_ms: 0.423308\n' +
    "      type: 'suite'\n" +
    '      ...\n' +
    '    # Subtest: nugetGitLabUrlBase\n' +
    '    ok 2 - nugetGitLabUrlBase\n' +
    '      ---\n' +
    '      duration_ms: 0.209459\n' +
    "      type: 'suite'\n" +
    '      ...\n' +
    '    # Subtest: nugetGitLabUrl\n' +
    '    ok 3 - nugetGitLabUrl\n' +
    '      ---\n' +
    '      duration_ms: 0.120995\n' +
    "      type: 'suite'\n" +
    '      ...\n' +
    '    # Subtest: getGitlabNugetRegistryPair\n' +
    '        # Subtest: is a function\n' +
    '        ok 1 - is a function\n' +
    '          ---\n' +
    '          duration_ms: 0.713669\n' +
    '          ...\n' +
    '        # Subtest: sufficient token permissions\n' +
    '        ok 2 - sufficient token permissions # TODO\n' +
    '          ---\n' +
    '          duration_ms: 0.132396\n' +
    '          ...\n' +
    '        # Subtest: insufficient token permissions\n' +
    '        ok 3 - insufficient token permissions # TODO\n' +
    '          ---\n' +
    '          duration_ms: 0.180176\n' +
    '          ...\n' +
    '        # Subtest: custom url\n' +
    '        ok 4 - custom url # TODO\n' +
    '          ---\n' +
    '          duration_ms: 0.206825\n' +
    '          ...\n' +
    '        # Subtest: custom token\n' +
    '        ok 5 - custom token # TODO\n' +
    '          ---\n' +
    '          duration_ms: 0.141243\n' +
    '          ...\n' +
    '        1..5\n' +
    '    ok 4 - getGitlabNugetRegistryPair\n' +
    '      ---\n' +
    '      duration_ms: 2.31521\n' +
    "      type: 'suite'\n" +
    '      ...\n' +
    '    1..4\n' +
    'ok 4 - dotnetGLPR\n' +
    '  ---\n' +
    '  duration_ms: 4.671677\n' +
    "  type: 'suite'\n" +
    '  ...\n' +
    '# Subtest: dotnetHelpers\n' +
    '    # Subtest: configurePrepareCmd\n' +
    '    ok 1 - configurePrepareCmd # TODO\n' +
    '      ---\n' +
    '      duration_ms: 1.216906\n' +
    '      ...\n' +
    '    # Subtest: nugetDefault is as expected\n' +
    '    ok 2 - nugetDefault is as expected\n' +
    '      ---\n' +
    '      duration_ms: 0.707157\n' +
    '      ...\n' +
    '    # Subtest: configureDotnetNugetPush works\n' +
    '    ok 3 - configureDotnetNugetPush works # TODO pushToGitHub adds github defaults\n' +
    '      ---\n' +
    '      duration_ms: 0.152414\n' +
    '      ...\n' +
    '    1..3\n' +
    'ok 5 - dotnetHelpers\n' +
    '  ---\n' +
    '  duration_ms: 3.718673\n' +
    "  type: 'suite'\n" +
    '  ...\n' +
    '1..5\n' +
    '# tests 23\n' +
    '# suites 10\n' +
    '# pass 11\n' +
    '# fail 1\n' +
    '# cancelled 0\n' +
    '# skipped 0\n' +
    '# todo 11\n' +
    '# duration_ms 468.588179\n' +
    'husky - pre-commit script failed (code 1)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
Error: Command failed with exit code 1: git commit -m chore(release): 2.5.0 [skip ci]

## [2.5.0](https://github.com/halospv3/hce.shared/compare/v2.4.3...v2.5.0) (2024-06-04)

### Features

* overhaul dotnetGHPR; misc refactors ([8d0a1d6](https://github.com/halospv3/hce.shared/commit/8d0a1d657e7f4754881c9a130fd4aa8191fb3e81))

### Bug Fixes

* **deps:** update dependency conventional-changelog-conventionalcommits to v8 ([e1defcd](https://github.com/halospv3/hce.shared/commit/e1defcd94ba51eda7384c1ca87f33c9928610e20))
* **deps:** update semantic-release monorepo ([39fcf98](https://github.com/halospv3/hce.shared/commit/39fcf988fe55b894e269d64de1b48c7f8dfb950c))


> @halospv3/hce.shared-config@2.3.1 check
> npm run type && npm run test && npm run lint


> @halospv3/hce.shared-config@2.3.1 type
> tsc --build


> @halospv3/hce.shared-config@2.3.1 pretest
> npm run build


> @halospv3/hce.shared-config@2.3.1 build
> packemon build --addExports --addFiles --declaration --loadConfigs

[@halospv3/hce.shared-config:HCE] Entry module "src/semanticReleaseConfigDotnet.ts" is using named and default exports together. Consumers of your bundle will have to use `chunk.default` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning. (id=/home/runner/work/HCE.Shared/HCE.Shared/src/semanticReleaseConfigDotnet.ts)
@halospv3/hce.shared-config
  ◼ cjs (38.87 kB) ◼ dts 2.2s

> @halospv3/hce.shared-config@2.3.1 test
> node --test --import tsx ./tests/**/*.test.ts

TAP version 13
...
# Subtest: dotnetGHPR
    # Subtest: getGithubNugetRegistryPair
        # Subtest: getGitHubNugetRegistryPair is function
        ok 1 - getGitHubNugetRegistryPair is function
          ---
          duration_ms: 0.339873
          ...
        # Subtest: can return when classic or workflow GITHUB_TOKEN or GH_TOKEN is defined with write:packages.
        not ok 2 - can return when classic or workflow GITHUB_TOKEN or GH_TOKEN is defined with write:packages.
          ---
          duration_ms: 9.739429
          location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:3360'
          failureType: 'testCodeFailure'
          error: |-
            Expected values to be strictly equal:
            + actual - expected
            
            + TypeError: The environment variable GITHUB_TOKEN is undefined!
            +     at tokenCanWritePackages (/home/runner/work/HCE.Shared/HCE.Shared/cjs/dotnet/dotnetGHPR.cjs:17:39)
            +     at TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:154:31)
            +     at Test.runInAsyncScope (node:async_hooks:206:9)
            +     at Test.run (node:internal/test_runner/test:824:25)
            +     at Suite.processPendingSubtests (node:internal/test_runner/test:533:18)
            +     at Test.postRun (node:internal/test_runner/test:923:19)
            +     at Test.run (node:internal/test_runner/test:866:12)
            +     at async Promise.all (index 0)
            +     at async Suite.run (node:internal/test_runner/test:1183:7)
            +     at async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)
            - true
          code: 'ERR_ASSERTION'
          name: 'AssertionError'
          expected: true
          actual:
          error: 'The environment variable GITHUB_TOKEN is undefined!'
          name: 'TypeError'
          stack: |-
            tokenCanWritePackages (/home/runner/work/HCE.Shared/HCE.Shared/cjs/dotnet/dotnetGHPR.cjs:17:39)
            TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:154:31)
            Test.runInAsyncScope (node:async_hooks:206:9)
            Test.run (node:internal/test_runner/test:824:25)
            Suite.processPendingSubtests (node:internal/test_runner/test:533:18)
            Test.postRun (node:internal/test_runner/test:923:19)
            Test.run (node:internal/test_runner/test:866:12)
            async Promise.all (index 0)
            async Suite.run (node:internal/test_runner/test:1183:7)
            async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)
          operator: 'strictEqual'
          stack: |-
            TestContext.<anonymous> (/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:161:5)
            async Test.run (node:internal/test_runner/test:825:9)
            async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)
          ...
        # Subtest: mock insufficient token
        ok 3 - mock insufficient token # TODO
          ---
          duration_ms: 0.143618
          ...
        # Subtest: mock sufficient token
        ok 4 - mock sufficient token # TODO
          ---
          duration_ms: 0.141574
          ...
        # Subtest: mock custom url
        ok 5 - mock custom url # TODO
          ---
          duration_ms: 0.117739
          ...
        1..5
    not ok 3 - getGithubNugetRegistryPair
      ---
      duration_ms: 10.990448
      type: 'suite'
      location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:2842'
      failureType: 'subtestsFailed'
      error: '1 subtest failed'
      code: 'ERR_TEST_FAILURE'
      ...
    1..3
not ok 3 - dotnetGHPR
  ---
  duration_ms: 17.527646
  type: 'suite'
  location: '/home/runner/work/HCE.Shared/HCE.Shared/tests/dotnet/dotnetGHPR.test.ts:1:708'
  failureType: 'subtestsFailed'
  error: '1 subtest failed'
  code: 'ERR_TEST_FAILURE'
  ...
# Subtest: dotnetGLPR
    # Subtest: GitLabTokenEnvVar
    ok 1 - GitLabTokenEnvVar
      ---
      duration_ms: 0.423308
      type: 'suite'
      ...
    # Subtest: nugetGitLabUrlBase
    ok 2 - nugetGitLabUrlBase
      ---
      duration_ms: 0.209459
      type: 'suite'
      ...
    # Subtest: nugetGitLabUrl
    ok 3 - nugetGitLabUrl
      ---
      duration_ms: 0.120995
      type: 'suite'
      ...
    # Subtest: getGitlabNugetRegistryPair
        # Subtest: is a function
        ok 1 - is a function
          ---
          duration_ms: 0.713669
          ...
        # Subtest: sufficient token permissions
        ok 2 - sufficient token permissions # TODO
          ---
          duration_ms: 0.132396
          ...
        # Subtest: insufficient token permissions
        ok 3 - insufficient token permissions # TODO
          ---
          duration_ms: 0.180176
          ...
        # Subtest: custom url
        ok 4 - custom url # TODO
          ---
          duration_ms: 0.206825
          ...
        # Subtest: custom token
        ok 5 - custom token # TODO
          ---
          duration_ms: 0.141243
          ...
        1..5
    ok 4 - getGitlabNugetRegistryPair
      ---
      duration_ms: 2.31521
      type: 'suite'
      ...
    1..4
ok 4 - dotnetGLPR
  ---
  duration_ms: 4.671677
  type: 'suite'
  ...
# Subtest: dotnetHelpers
    # Subtest: configurePrepareCmd
    ok 1 - configurePrepareCmd # TODO
      ---
      duration_ms: 1.216906
      ...
    # Subtest: nugetDefault is as expected
    ok 2 - nugetDefault is as expected
      ---
      duration_ms: 0.707157
      ...
    # Subtest: configureDotnetNugetPush works
    ok 3 - configureDotnetNugetPush works # TODO pushToGitHub adds github defaults
      ---
      duration_ms: 0.152414
      ...
    1..3
ok 5 - dotnetHelpers
  ---
  duration_ms: 3.718673
  type: 'suite'
  ...
1..5
# tests 23
# suites 10
# pass 11
# fail 1
# cancelled 0
# skipped 0
# todo 11
# duration_ms 468.588179
husky - pre-commit script failed (code 1)
```

**Comment by BinToss** [comment]
fixed by cf0caa7015bef4dac18bf6fb583ac8229ae6c526
